imports:
    - { resource: "local/" }

pimcore:
    product_registration:
        instance_identifier: 4qFkEocbx9ZAbR4rJWTq1t
        product_key: "eyJwYXlsb2FkIjoie1wiaWRcIjpcIjdlOTk3NDk0ZTY2MDJlZDE1ZDdkZDcyYWNmMjljNzYzZGM2ZDUyMTY4OGVhMmFhMjQ1YWM0YTRlYWU3YjczZWVcIixcInRpbWVzdGFtcFwiOjE3NTYyOTkxMDR9Iiwic2lnbmF0dXJlIjoiTUVVQ0lRQ29TVTkyTzdEU2c0b25pMjhUT2Y3R3Z5MWFmanREeGRwcnoySVd2S2JFMHdJZ0llMlJyZnJ2SUpDdGdndElraU9XRGRwT0hna0tWYjlBaXpZSHBoczVheWs9In0="

    models:
        class_overrides:
            'Pimcore\Bundle\GlossaryBundle\Model\Glossary': 'Test\Override\GlossaryBundle\Model\Glossary'